-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aerostore_verified]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AerostoreExtracted

/-- [aerostore_verified::canonical_buckets_sort]: loop body 1:
    Source: 'aerostore_verified/src/lib.rs', lines 1:0-42:9
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_sort_loop0_loop0.body
  (output : alloc.vec.Vec Std.Usize) (bucket : Std.Usize)
  (position : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := alloc.vec.Vec.len output
  if position < i
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        output position
    if i1 < bucket
    then let position1 ← position + 1#usize
         ok (cont position1)
    else ok (done position)
  else ok (done position)

/-- [aerostore_verified::canonical_buckets_sort]: loop 1:
    Source: 'aerostore_verified/src/lib.rs', lines 1:0-42:9
    Visibility: public -/
@[rust_loop]
def canonical_buckets_sort_loop0_loop0
  (output : alloc.vec.Vec Std.Usize) (bucket : Std.Usize)
  (position : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun position1 => canonical_buckets_sort_loop0_loop0.body output bucket
      position1)
    position

/-- [aerostore_verified::canonical_buckets_sort]: loop body 2:
    Source: 'aerostore_verified/src/lib.rs', lines 51:12-63:13
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_sort_loop0_loop1.body
  (position : Std.Usize) (output : alloc.vec.Vec Std.Usize) (shift : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.Usize) × Std.Usize) (alloc.vec.Vec
    Std.Usize))
  := do
  if shift > position
  then
    let i ← shift - 1#usize
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        output i
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        output shift
    let output1 := index_mut_back i1
    ok (cont (output1, i))
  else ok (done output)

/-- [aerostore_verified::canonical_buckets_sort]: loop 2:
    Source: 'aerostore_verified/src/lib.rs', lines 51:12-63:13
    Visibility: public -/
@[rust_loop]
def canonical_buckets_sort_loop0_loop1
  (output : alloc.vec.Vec Std.Usize) (position : Std.Usize) (shift : Std.Usize)
  :
  Result (alloc.vec.Vec Std.Usize)
  := do
  loop
    (fun (output1, shift1) => canonical_buckets_sort_loop0_loop1.body position
      output1 shift1)
    (output, shift)

/-- [aerostore_verified::canonical_buckets_sort]: loop body 3:
    Source: 'aerostore_verified/src/lib.rs', lines 51:12-63:13
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_sort_loop0_loop2.body
  (position : Std.Usize) (output : alloc.vec.Vec Std.Usize) (shift : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.Usize) × Std.Usize) (alloc.vec.Vec
    Std.Usize))
  := do
  if shift > position
  then
    let i ← shift - 1#usize
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        output i
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        output shift
    let output1 := index_mut_back i1
    ok (cont (output1, i))
  else ok (done output)

/-- [aerostore_verified::canonical_buckets_sort]: loop 3:
    Source: 'aerostore_verified/src/lib.rs', lines 51:12-63:13
    Visibility: public -/
@[rust_loop]
def canonical_buckets_sort_loop0_loop2
  (output : alloc.vec.Vec Std.Usize) (position : Std.Usize) (shift : Std.Usize)
  :
  Result (alloc.vec.Vec Std.Usize)
  := do
  loop
    (fun (output1, shift1) => canonical_buckets_sort_loop0_loop2.body position
      output1 shift1)
    (output, shift)

/-- [aerostore_verified::canonical_buckets_sort]: loop body 0:
    Source: 'aerostore_verified/src/lib.rs', lines 1:0-77:1
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_sort_loop0.body
  (input : Slice Std.Usize) (bucket_count : Std.Usize)
  (output : alloc.vec.Vec Std.Usize) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.Usize) × Std.Usize)
    (core.result.Result (alloc.vec.Vec Std.Usize) Std.Usize))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let bucket ← Slice.index_usize input i
    if bucket >= bucket_count
    then ok (done (core.result.Result.Err bucket))
    else
      let position ← canonical_buckets_sort_loop0_loop0 output bucket 0#usize
      let i2 := alloc.vec.Vec.len output
      if position = i2
      then
        let output1 ← alloc.vec.Vec.push output bucket
        let i3 := alloc.vec.Vec.len output1
        let shift ← i3 - 1#usize
        let output2 ←
          canonical_buckets_sort_loop0_loop1 output1 position shift
        let (_, index_mut_back) ←
          alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
            Std.Usize) output2 position
        let i4 ← i + 1#usize
        let output3 := index_mut_back bucket
        ok (cont (output3, i4))
      else
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
            output position
        if i3 != bucket
        then
          let output1 ← alloc.vec.Vec.push output bucket
          let i4 := alloc.vec.Vec.len output1
          let shift ← i4 - 1#usize
          let output2 ←
            canonical_buckets_sort_loop0_loop2 output1 position shift
          let (_, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              Std.Usize) output2 position
          let i5 ← i + 1#usize
          let output3 := index_mut_back bucket
          ok (cont (output3, i5))
        else let i4 ← i + 1#usize
             ok (cont (output, i4))
  else ok (done (core.result.Result.Ok output))

/-- [aerostore_verified::canonical_buckets_sort]: loop 0:
    Source: 'aerostore_verified/src/lib.rs', lines 1:0-77:1
    Visibility: public -/
@[rust_loop]
def canonical_buckets_sort_loop0
  (input : Slice Std.Usize) (bucket_count : Std.Usize)
  (output : alloc.vec.Vec Std.Usize) (i : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Std.Usize) Std.Usize)
  := do
  loop
    (fun (output1, i1) => canonical_buckets_sort_loop0.body input bucket_count
      output1 i1)
    (output, i)

/-- [aerostore_verified::canonical_buckets_sort]:
    Source: 'aerostore_verified/src/lib.rs', lines 10:0-77:1
    Visibility: public -/
@[reducible]
def canonical_buckets_sort
  (input : Slice Std.Usize) (bucket_count : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Std.Usize) Std.Usize)
  := do
  canonical_buckets_sort_loop0 input bucket_count (alloc.vec.Vec.new Std.Usize)
    0#usize

/-- [aerostore_verified::canonical_buckets_bitmap]: loop body 1:
    Source: 'aerostore_verified/src/lib.rs', lines 102:4-113:5
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_bitmap_loop0_loop0.body
  (bucket_count : Std.Usize) (present : alloc.vec.Vec Bool)
  (bucket : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Bool) × Std.Usize) (alloc.vec.Vec Bool))
  := do
  if bucket < bucket_count
  then
    let present1 ← alloc.vec.Vec.push present false
    let bucket1 ← bucket + 1#usize
    ok (cont (present1, bucket1))
  else ok (done present)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop 1:
    Source: 'aerostore_verified/src/lib.rs', lines 102:4-113:5
    Visibility: public -/
@[rust_loop]
def canonical_buckets_bitmap_loop0_loop0
  (bucket_count : Std.Usize) (present : alloc.vec.Vec Bool)
  (bucket : Std.Usize) :
  Result (alloc.vec.Vec Bool)
  := do
  loop
    (fun (present1, bucket1) => canonical_buckets_bitmap_loop0_loop0.body
      bucket_count present1 bucket1)
    (present, bucket)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop body 2:
    Source: 'aerostore_verified/src/lib.rs', lines 115:4-130:5
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_bitmap_loop0_loop1.body
  (input : Slice Std.Usize) (i : Std.Usize) (present : alloc.vec.Vec Bool) :
  Result (ControlFlow (Std.Usize × (alloc.vec.Vec Bool)) (alloc.vec.Vec Bool))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let i2 ← Slice.index_usize input i
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Bool)
        present i2
    let i3 ← i + 1#usize
    let present1 := index_mut_back true
    ok (cont (i3, present1))
  else ok (done present)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop 2:
    Source: 'aerostore_verified/src/lib.rs', lines 115:4-130:5
    Visibility: public -/
@[rust_loop]
def canonical_buckets_bitmap_loop0_loop1
  (input : Slice Std.Usize) (i : Std.Usize) (present : alloc.vec.Vec Bool) :
  Result (alloc.vec.Vec Bool)
  := do
  loop
    (fun (i1, present1) => canonical_buckets_bitmap_loop0_loop1.body input i1
      present1)
    (i, present)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop body 3:
    Source: 'aerostore_verified/src/lib.rs', lines 133:4-151:5
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_bitmap_loop0_loop2.body
  (bucket_count : Std.Usize) (present : alloc.vec.Vec Bool)
  (bucket : Std.Usize) (output : alloc.vec.Vec Std.Usize) :
  Result (ControlFlow (Std.Usize × (alloc.vec.Vec Std.Usize)) (alloc.vec.Vec
    Std.Usize))
  := do
  if bucket < bucket_count
  then
    let b ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Bool) present
        bucket
    let output1 ← if b
                    then alloc.vec.Vec.push output bucket
                    else ok output
    let bucket1 ← bucket + 1#usize
    ok (cont (bucket1, output1))
  else ok (done output)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop 3:
    Source: 'aerostore_verified/src/lib.rs', lines 133:4-151:5
    Visibility: public -/
@[rust_loop]
def canonical_buckets_bitmap_loop0_loop2
  (bucket_count : Std.Usize) (present : alloc.vec.Vec Bool)
  (bucket : Std.Usize) (output : alloc.vec.Vec Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  loop
    (fun (bucket1, output1) => canonical_buckets_bitmap_loop0_loop2.body
      bucket_count present bucket1 output1)
    (bucket, output)

/-- [aerostore_verified::canonical_buckets_bitmap]: loop body 0:
    Source: 'aerostore_verified/src/lib.rs', lines 86:4-154:1
    Visibility: public -/
@[rust_loop_body]
def canonical_buckets_bitmap_loop0.body
  (input : Slice Std.Usize) (bucket_count : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (core.result.Result (alloc.vec.Vec Std.Usize)
    Std.Usize))
  := do
  let i1 := Slice.len input
  if i < i1
  then
    let i2 ← Slice.index_usize input i
    if i2 >= bucket_count
    then ok (done (core.result.Result.Err i2))
    else let i3 ← i + 1#usize
         ok (cont i3)
  else
    let present ←
      canonical_buckets_bitmap_loop0_loop0 bucket_count (alloc.vec.Vec.new
        Bool) 0#usize
    let present1 ← canonical_buckets_bitmap_loop0_loop1 input 0#usize present
    let output ←
      canonical_buckets_bitmap_loop0_loop2 bucket_count present1 0#usize
        (alloc.vec.Vec.new Std.Usize)
    ok (done (core.result.Result.Ok output))

/-- [aerostore_verified::canonical_buckets_bitmap]: loop 0:
    Source: 'aerostore_verified/src/lib.rs', lines 86:4-154:1
    Visibility: public -/
@[rust_loop]
def canonical_buckets_bitmap_loop0
  (input : Slice Std.Usize) (bucket_count : Std.Usize) (i : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Std.Usize) Std.Usize)
  := do
  loop
    (fun i1 => canonical_buckets_bitmap_loop0.body input bucket_count i1)
    i

/-- [aerostore_verified::canonical_buckets_bitmap]:
    Source: 'aerostore_verified/src/lib.rs', lines 84:0-154:1
    Visibility: public -/
@[reducible]
def canonical_buckets_bitmap
  (input : Slice Std.Usize) (bucket_count : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Std.Usize) Std.Usize)
  := do
  canonical_buckets_bitmap_loop0 input bucket_count 0#usize

/-- [aerostore_verified::stamp_precedes_snapshot]:
    Source: 'aerostore_verified/src/lib.rs', lines 160:0-162:1
    Visibility: public -/
def stamp_precedes_snapshot
  (stamp : Std.U64) (transaction_id : Std.U64) : Result Bool := do
  ok (stamp < transaction_id)

end AerostoreExtracted
