"""Independently stream scheduled jobs and transactions; inspect existing oracle witness."""
from pathlib import Path
from collections import Counter,defaultdict
from datetime import datetime,timezone
import hashlib,json,math,sys
root=Path.cwd();base=root/'target/maintenance-final-validation';sys.path.insert(0,str(root/'scripts'))
from qualify_hyperfeed import snapshot_sources,sha256
build=json.loads((base/'build-provenance.json').read_text());results=[];corpora=[];seeds=[]
def q99(values):return sorted(values)[(len(values)*99+99)//100-1]/1000
for label in ['cadence-native','cadence-postgres']:
 campaign_path=base/label/'campaign.json';campaign=json.loads(campaign_path.read_text());assert campaign['passed'] and campaign['completed'] and campaign['source_stable'];assert campaign['source_before']==campaign['source_after']==build['source_before'];assert campaign['binary_before_sha256']==campaign['binary_after_sha256']==build['binary_sha256']
 assert len(campaign['trials'])==1;campaign_before=sha256(campaign_path)
 trial=campaign['trials'][0];assert trial['exit_code']==0 and not trial['timed_out'] and not trial['error'] and trial['source_stable'];assert trial['source_before_sha256']==trial['source_after_sha256']==build['source_before']['sha256'];assert trial['binary_before_sha256']==trial['binary_after_sha256']==build['binary_sha256'];assert trial['report']['completed'] and trial['report']['passed'] and len(trial['report']['runs'])==1
 config=trial['config'];run=trial['report']['runs'][0];assert run['execution_completed'] and run['passed'] and run['history_checked'] and run['oracle_status']=='Valid';case=Path(run['evidence_directory']);artifact_names=['history.jsonl','initial.json','final.json','serial-witness.json','offered-schedule.json'];artifacts_before={name:sha256(case/name) for name in artifact_names};admission=run['admission_started_ns'];assert config['seconds']==601 and config['arrival_rate']==32 and config['workers']==4 and config['families']==16 and config['seed']==20260925;assert config['maintenance_mode']=='sweep';assert config['projection_interval_seconds']==config['housekeeping_interval_seconds']==300;assert config['dispatch']=='identity' and config['signature_pattern']=='both' and config['affinity_ttl_ms']==0 and config['evidence']=='full';assert config['projection_batch_size']==4 and config['housekeeping_batch_size']==32 and config['max_maintenance_batches']==4096
 schedule=json.loads((case/'offered-schedule.json').read_text());assert schedule['offered_messages']==19236 and schedule['offered_by_worker']==[4808]*4+[2,2];assert schedule['admission_started_ns']==admission and schedule['admission_finished_ns']==admission+601*10**9
 ids=set();fg=set();by_flight=defaultdict(list);groups=defaultdict(list);outcomes=defaultdict(Counter);transactions=Counter();successful=[];samples=[];corpus=hashlib.sha256();last_finish=[0]*6
 names={'Plan':'plan','Position':'position','GlobalProject':'global_projection','GlobalHousekeeping':'global_housekeeping'}
 with (case/'history.jsonl').open() as stream:
  for line in stream:
   row=json.loads(line);receipt=row['receipt'];message=receipt['message'];mid=message['id'];effect=receipt['body']['outcome'];cls=row['workload_class'];worker=row['worker'];kind=message['kind'];name=kind if isinstance(kind,str) else next(iter(kind));canonical=names[name]
   assert mid not in ids;ids.add(mid);first=row['message_started_ns'];start=receipt['started'];finish=receipt['finished'];received=row['received_ns'];scheduled=row['scheduled_ns'];assert admission<=scheduled<=first<=start<finish<=received;assert first>=last_finish[worker];last_finish[worker]=finish;assert row['end_to_end_latency_ns']==received-scheduled and row['service_latency_ns']==finish-first
   assert message['event_time_units_per_second']==10**9 and message['event_time']==1700000000000000000+scheduled-admission
   transactions[canonical]+=1;successful.append((mid,start,finish))
   for key,value in effect.items():
    if key!='family':outcomes[canonical]['duplicate_messages' if key=='duplicate' else key]+=len(value) if key=='outputs' else int(value)
   if cls=='foreground':
    sequence=mid-1000000;identity=sequence%12;ordinal=sequence//12;fg.add(sequence);assert 0<=sequence<19232 and worker==identity%4 and row['logical_identity']==identity and row['foreground_ordinal']==ordinal;assert scheduled==admission+sequence*10**9//32 and name==('Plan' if ordinal%16==0 else 'Position') and message['source']==1<<(ordinal%3);assert message['creation']=='ExistingOnly';assert effect['updated_views']>0 and not effect['missing_family'] and not effect['allocation_deferred'] and not effect['duplicate'] and effect['ignored_stale']==0;assert row['job_completed'] and row['batch_index'] is None
    by_flight[identity].append((ordinal,first,finish));samples.append({'class':cls,'worker':worker,'scheduled':scheduled,'first':first,'finish':finish,'received':received,'retries':row['retries'],'positive':True})
   else:
    bit=int(cls=='housekeeping');job=row['job_id'];ordinal=(job-4000000000-bit)//2;assert worker==4+bit and ordinal in (0,1) and job==4000000000+2*ordinal+bit;assert row['job_ordinal']==ordinal and scheduled==admission+(ordinal+1)*300*10**9;assert row['logical_identity'] is None and row['foreground_ordinal'] is None
    batches=groups[job];index=len(batches);assert row['batch_index']==index and mid==8000000000+(job-4000000000)*4096+index;assert name==('GlobalHousekeeping' if bit else 'GlobalProject');limit=32 if bit else 4;assert kind[name]['limit']==limit;query='GlobalExpired' if bit else 'GlobalDue';ops=receipt['body']['operations'];queries=[op['Query'] for op in ops if 'Query' in op and query in op['Query']['query']];assert len(queries)==1;expected_at=1700000000000000000+(ordinal+1)*300*10**9;cutoff_key='before' if bit else 'at';cutoff=expected_at-3600*10**9 if bit else expected_at;assert kind[name]=={cutoff_key:cutoff,'limit':limit};assert queries[0]['query']=={query:{cutoff_key:cutoff}}
    selected=effect['expired_records' if bit else 'claimed_events'];terminal=selected==0;assert min(len(queries[0]['rows']),limit)==selected;assert row['maintenance_terminal']==row['job_completed']==terminal;assert not batches or not batches[-1]['job_completed'];assert not batches or kind==batches[0]['receipt']['message']['kind'];assert not terminal or (len(ops)==1 and queries[0]['rows']==[])
    batches.append(row)
 # Compare fixed corpus in deterministic foreground sequence order, independent of completion order.
 with (case/'history.jsonl').open() as stream:
  messages=[json.loads(line)['receipt']['message'] for line in stream]
 for message in sorted((m for m in messages if m['id']<4000000000),key=lambda m:m['id']):corpus.update(json.dumps(message,sort_keys=True,separators=(',',':')).encode())
 corpora.append(corpus.hexdigest());assert fg==set(range(19232));assert len(groups)==4;assert len(run['maintenance_jobs'])==4 and {job['job_id'] for job in run['maintenance_jobs']}==set(groups)
 ticks=[]
 for job in run['maintenance_jobs']:
  rows=groups[job['job_id']];last=rows[-1];assert last['job_completed'];assert job['batches']==len(rows) and job['nonempty_batches']==len(rows)-1 and job['terminal_batches']==1 and job['terminal_empty'];assert job['started_ns']==rows[0]['message_started_ns'] and job['finished_ns']==last['receipt']['finished'] and job['received_ns']==last['received_ns'];assert job['retries']==sum(r['retries'] for r in rows);field='claimed_events' if job['class']=='projection' else 'expired_records';assert job['processed_rows']==sum(r['receipt']['body']['outcome'][field] for r in rows);assert job['processed_rows']>0
  samples.append({'class':job['class'],'worker':job['worker'],'scheduled':job['scheduled_ns'],'first':job['started_ns'],'finish':job['finished_ns'],'received':job['received_ns'],'retries':job['retries'],'positive':True});ticks.append({'class':job['class'],'ordinal':job['job_ordinal'],'offset_seconds':(job['scheduled_ns']-admission)/1e9,'batches':job['batches'],'processed_rows':job['processed_rows'],'retries':job['retries'],'completion_latency_ms':(job['received_ns']-job['scheduled_ns'])/1e6})
 assert run['completed_messages']==19236 and run['completed_transactions']==len(ids)==run['store_metrics']['commits'];assert run['completed_by_worker']==[4808]*4+[2,2];assert run['transaction_kinds']==transactions
 for name,counts in outcomes.items():assert dict(counts)==run['per_kind'][name]['outcomes'];assert run['per_kind'][name]['transactions']==transactions[name]
 for lane in by_flight.values():
  lane.sort();assert [v[0] for v in lane]==list(range(len(lane)));assert all(a[2]<=b[1] for a,b in zip(lane,lane[1:]))
 for cls in ['foreground','projection','housekeeping','maintenance']:
  selected=[s for s in samples if s['class']==cls or cls=='maintenance' and s['class']!='foreground'];reported=run['workload_classes'][cls];assert reported['completed']==reported['offered']==len(selected);assert reported['retries']==sum(s['retries'] for s in selected);assert reported['positive_effect_jobs']==len(selected)
  for field,end,start in [('p99_us_including_retries','received','scheduled'),('service_latency_p99_us_including_retries','finish','first'),('arrival_queue_delay_p99_us','first','scheduled')]:assert reported[field]==q99([s[end]-s[start] for s in selected])
 for worker,activity in enumerate(run['worker_activity']):
  selected=[s for s in samples if s['worker']==worker];assert activity['busy_ns']==sum(s['finish']-s['first'] for s in selected);assert activity['retries']==sum(s['retries'] for s in selected)
 assert admission+601*10**9<=run['workload_completed_ns']<=run['workers_stopped_ns']<=run['drain_confirmed_ns'];elapsed=(run['drain_confirmed_ns']-admission)/1e9;assert run['elapsed_seconds_including_drain']==elapsed and math.isclose(run['completed_messages_per_second_including_drain'],19236/elapsed,rel_tol=1e-12)
 witness=json.loads((case/'serial-witness.json').read_text());order=witness['order'];assert witness['status']=='Valid' and len(order)==len(ids) and set(order)==ids;position={mid:i for i,mid in enumerate(order)};finished=sorted(successful,key=lambda v:v[2]);cursor=0;maximum=-1
 for mid,start,finish in sorted(successful,key=lambda v:v[1]):
  while cursor<len(finished) and finished[cursor][2]<=start:maximum=max(maximum,position[finished[cursor][0]]);cursor+=1
  assert maximum<position[mid]
 assert run['correctness_history_verified'] and run['global_maintenance_sweep_complete'];assert trial['assessment']['representative_cadence_coverage_passed'] and trial['assessment']['foreground_effect_coverage_passed'];assert not trial['assessment']['qualified_capacity_trial'] and not run['population_turnover_tested'];seeds.append(sha256(case/'initial.json'))
 results.append({'engine':config['engine'],'completed_jobs':run['completed_messages'],'completed_transactions':len(ids),'oracle_status':run['oracle_status'],'foreground_useful_and_ordered':True,'maintenance_ticks':sorted(ticks,key=lambda t:(t['offset_seconds'],t['class'])),'representative_cadence_coverage':True,'capacity_qualified':False,'retention_samples':len(run['retention_samples']) if 'retention_samples' in run else None,'continuous_elapsed_seconds':elapsed,'campaign_sha256':sha256(campaign_path),'evidence_directory':str(case),'artifacts':{name:sha256(case/name) for name in artifact_names}});assert results[-1]['artifacts']==artifacts_before and sha256(campaign_path)==campaign_before
assert len(set(corpora))==1 and len(set(seeds))==1;assert snapshot_sources()==build['source_before'];assert sha256(base/'benchmark-final')==build['binary_sha256']
review={'passed':True,'review_helper_sha256':sha256(Path(__file__)),'created_at':datetime.now(timezone.utc).isoformat(),'scope':'Two complete sweeps per timer at real300/600s deadlines on each engine with concurrent foreground input; independent raw schedule/accounting/latency/witness-order audit. Existing semantic serial oracle checked, not independently rerun. Shared host with concurrent checks; no comparative performance, capacity, turnover, memory plateau or physicalMMHF claim.','source_sha256':build['source_before']['sha256'],'binary_sha256':build['binary_sha256'],'foreground_corpus_sha256':corpora[0],'initial_rows_sha256':seeds[0],'runs':results};(base/'cadence-review.json').write_text(json.dumps(review,indent=2)+'\n');print(json.dumps(review,indent=2))
