// Generated from native index_lookup; see generate.py for the boundary.
// Conditional proof of the native predicate dependency-capture loop.
// Primitive stamp visibility under held bucket guards remains an assumption.
use vstd::prelude::*;
mod bucket_kernels {
    // Generated by verification/verus/generate.py; do not edit.
use vstd::prelude::*;
verus! {
// This contract and its proof-library roots are frozen by the acceptance gate.
broadcast use vstd::seq_lib::group_seq_properties;

pub open spec fn sorted(values: Seq<usize>) -> bool {
    forall|i: int, j: int| 0 <= i < j < values.len() ==> values[i] < values[j]
}

pub open spec fn in_range(values: Seq<usize>, count: usize) -> bool {
    forall|i: int| 0 <= i < values.len() ==> values[i] < count
}

pub open spec fn first_invalid(input: Seq<usize>, count: usize, bad: usize) -> bool {
    exists|i: int| 0 <= i < input.len()
        && input[i] == bad && bad >= count
        && forall|j: int| 0 <= j < i ==> input[j] < count
}

pub open spec fn canonical(input: Seq<usize>, count: usize, output: Seq<usize>) -> bool {
    sorted(output) && in_range(output, count)
        && output.len() <= input.len() && output.len() <= count
        && forall|b: usize| output.contains(b) <==> input.contains(b)
}

pub open spec fn bucket_result(input: Seq<usize>, count: usize, result: Result<Vec<usize>, usize>) -> bool {
    match result {
        Ok(output) => canonical(input, count, output@),
        Err(bad) => first_invalid(input, count, bad),
    }
}

proof fn first_invalid_witness(input: Seq<usize>, count: usize, i: int)
    requires 0 <= i < input.len(), input[i] >= count,
        forall|j: int| 0 <= j < i ==> input[j] < count,
    ensures first_invalid(input, count, input[i]),
{
    assert(exists|k: int| 0 <= k < input.len()
        && input[k] == input[i] && input[i] >= count
        && forall|j: int| 0 <= j < k ==> input[j] < count);
}

proof fn sorted_index_bound(values: Seq<usize>, i: int)
    requires sorted(values), 0 <= i < values.len(),
    ensures i <= values[i],
    decreases i,
{
    if i > 0 {
        sorted_index_bound(values, i - 1);
        assert(values[i - 1] < values[i]);
    }
}

proof fn insertion_membership(values: Seq<usize>, position: int, value: usize)
    requires 0 <= position <= values.len(),
    ensures forall|b: usize| #[trigger] values.insert(position, value).contains(b)
        <==> values.contains(b) || b == value,
{
    let inserted = values.insert(position, value);
    assert forall|b: usize| inserted.contains(b) <==> values.contains(b) || b == value by {
        if inserted.contains(b) {
            let j = choose|j: int| 0 <= j < inserted.len() && inserted[j] == b;
            if j < position {
                assert(values[j] == b);
            } else if j > position {
                assert(values[j - 1] == b);
            }
        }
        if values.contains(b) {
            let j = choose|j: int| 0 <= j < values.len() && values[j] == b;
            if j < position {
                assert(inserted[j] == b);
            } else {
                assert(inserted[j + 1] == b);
            }
        }
        if b == value { assert(inserted[position] == b); }
    }
}

proof fn sorted_range_bound(values: Seq<usize>, count: usize)
    requires sorted(values), in_range(values, count),
    ensures values.len() <= count,
{
    if values.len() > 0 {
        sorted_index_bound(values, values.len() - 1);
    }
}

proof fn membership_length_bound(values: Seq<usize>, input: Seq<usize>)
    requires sorted(values),
        forall|b: usize| values.contains(b) ==> input.contains(b),
    ensures values.len() <= input.len(),
{
    assert(values.no_duplicates());
    values.unique_seq_to_set();
    input.lemma_cardinality_of_set();
    values.to_set_ensures();
    input.to_set_ensures();
    assert(values.to_set().subset_of(input.to_set()));
    vstd::set_lib::lemma_len_subset(values.to_set(), input.to_set());
}

proof fn tail_membership(values: Seq<usize>)
    requires sorted(values), values.len() > 0,
    ensures forall|b: usize| #[trigger] values.drop_first().contains(b)
        <==> values.contains(b) && b != values[0],
{
    assert forall|b: usize| values.drop_first().contains(b)
        <==> values.contains(b) && b != values[0] by {
        if values.drop_first().contains(b) {
            let i = choose|i: int| 0 <= i < values.drop_first().len()
                && values.drop_first()[i] == b;
            assert(values[i + 1] == b);
        }
        if values.contains(b) && b != values[0] {
            let i = choose|i: int| 0 <= i < values.len() && values[i] == b;
            assert(i > 0);
            assert(values.drop_first()[i - 1] == b);
        }
    }
}

pub proof fn canonical_sequence_unique(left: Seq<usize>, right: Seq<usize>)
    requires sorted(left), sorted(right),
        forall|b: usize| left.contains(b) <==> right.contains(b),
    ensures left == right,
    decreases left.len() + right.len(),
{
    if left.len() == 0 {
        if right.len() > 0 { assert(left.contains(right[0])); }
        assert(left =~= right);
    } else {
        assert(right.contains(left[0]));
        assert(right.len() > 0);
        assert(left.contains(right[0]));
        let i = choose|i: int| 0 <= i < left.len() && left[i] == right[0];
        let j = choose|j: int| 0 <= j < right.len() && right[j] == left[0];
        assert(left[0] <= left[i]);
        assert(right[0] <= right[j]);
        assert(left[0] == right[0]);
        tail_membership(left);
        tail_membership(right);
        canonical_sequence_unique(left.drop_first(), right.drop_first());
        assert(left =~= right);
    }
}

pub proof fn first_invalid_unique(input: Seq<usize>, count: usize, left: usize, right: usize)
    requires first_invalid(input, count, left), first_invalid(input, count, right),
    ensures left == right,
{
    let i = choose|i: int| 0 <= i < input.len() && input[i] == left && left >= count
        && forall|j: int| 0 <= j < i ==> input[j] < count;
    let j = choose|j: int| 0 <= j < input.len() && input[j] == right && right >= count
        && forall|k: int| 0 <= k < j ==> input[k] < count;
    assert(i == j);
}

pub open spec fn equivalent_results(left: Result<Vec<usize>, usize>, right: Result<Vec<usize>, usize>) -> bool {
    match (left, right) {
        (Ok(a), Ok(b)) => a@ == b@,
        (Err(a), Err(b)) => a == b,
        _ => false,
    }
}

pub proof fn canonical_result_unique(input: Seq<usize>, count: usize,
    left: Result<Vec<usize>, usize>, right: Result<Vec<usize>, usize>)
    requires bucket_result(input, count, left), bucket_result(input, count, right),
    ensures equivalent_results(left, right),
{
    match (left, right) {
        (Ok(a), Ok(b)) => canonical_sequence_unique(a@, b@),
        (Err(a), Err(b)) => first_invalid_unique(input, count, a, b),
        (Ok(a), Err(b)) | (Err(b), Ok(a)) => {
            let i = choose|i: int| 0 <= i < input.len() && input[i] == b && b >= count
                && forall|j: int| 0 <= j < i ==> input[j] < count;
            assert(input.contains(b));
            assert(a@.contains(b));
            let j = choose|j: int| 0 <= j < a.len() && a@[j] == b;
            assert(a@[j] < count);
        }
    }
}










pub fn canonical_buckets_sort(input: &[usize], bucket_count: usize) -> (result: Result<Vec<usize>, usize>)/*PROOF-BEGIN*/
 ensures bucket_result(input@, bucket_count, result), /*PROOF-END*/ {
    let mut output: Vec<usize> = Vec::new();
    let mut i: usize = 0;
    while i < input.len()
    /*PROOF-BEGIN*/
        invariant
            i <= input.len(),
            output.len() <= i,
            sorted(output@),
            in_range(output@, bucket_count),
            forall|k: int| 0 <= k < i ==> input@[k] < bucket_count,
            forall|b: usize| output@.contains(b) <==> input@.take(i as int).contains(b),
        decreases input.len() - i,
    /*PROOF-END*/
    {
        let bucket = input[i];
        if bucket >= bucket_count {
            /*PROOF-BEGIN*/ proof { first_invalid_witness(input@, bucket_count, i as int); } /*PROOF-END*/
            return Err(bucket);
        }
        let mut position: usize = 0;
        while position < output.len() && output[position] < bucket
        /*PROOF-BEGIN*/
            invariant
                position <= output.len(),
                sorted(output@),
                forall|b: usize| output@.contains(b) <==> input@.take(i as int).contains(b),
                forall|j: int| 0 <= j < position ==> output@[j] < bucket,
            decreases output.len() - position,
        /*PROOF-END*/
        {
            position += 1;
        }
        if position == output.len() || output[position] != bucket {
            /*PROOF-BEGIN*/ proof {
                assert(forall|j: int| position <= j < output.len() ==> bucket < output@[j]);
                insertion_membership(output@, position as int, bucket);
            } /*PROOF-END*/
            /*PROOF-BEGIN*/ let ghost original = output@; /*PROOF-END*/
            output.push(bucket);
            let mut shift = output.len() - 1;
            while shift > position
            /*PROOF-BEGIN*/
                invariant
                    position <= shift <= original.len(),
                    output.len() == original.len() + 1,
                    forall|j: int| 0 <= j < shift ==> output@[j] == original[j],
                    forall|j: int| shift < j < output.len() ==> output@[j] == original[j - 1],
                decreases shift - position,
            /*PROOF-END*/
            {
                output[shift] = output[shift - 1];
                shift -= 1;
            }
            output[position] = bucket;
            /*PROOF-BEGIN*/ proof { assert(output@ =~= original.insert(position as int, bucket)); } /*PROOF-END*/
        } else {
            /*PROOF-BEGIN*/ proof { assert(output@.contains(bucket)); } /*PROOF-END*/
        }
        /*PROOF-BEGIN*/ proof {
            assert(input@.take((i + 1) as int) == input@.take(i as int).push(bucket));
            assert forall|b: usize| output@.contains(b) <==> input@.take((i + 1) as int).contains(b) by {};
        } /*PROOF-END*/
        i += 1;
    }
    /*PROOF-BEGIN*/ proof { sorted_range_bound(output@, bucket_count); } /*PROOF-END*/
    Ok(output)
}






pub fn canonical_buckets_bitmap(input: &[usize], bucket_count: usize) -> (result: Result<Vec<usize>, usize>)/*PROOF-BEGIN*/
 ensures bucket_result(input@, bucket_count, result), /*PROOF-END*/ {
    let mut i: usize = 0;
    while i < input.len()
    /*PROOF-BEGIN*/
        invariant
            i <= input.len(),
            forall|j: int| 0 <= j < i ==> input@[j] < bucket_count,
        decreases input.len() - i,
    /*PROOF-END*/
    {
        if input[i] >= bucket_count {
            /*PROOF-BEGIN*/ proof { first_invalid_witness(input@, bucket_count, i as int); } /*PROOF-END*/
            return Err(input[i]);
        }
        i += 1;
    }
    let mut present: Vec<bool> = Vec::new();
    let mut bucket: usize = 0;
    while bucket < bucket_count
    /*PROOF-BEGIN*/
        invariant
            bucket <= bucket_count,
            present.len() == bucket,
            forall|j: int| 0 <= j < present.len() ==> !present@[j],
        decreases bucket_count - bucket,
    /*PROOF-END*/
    {
        present.push(false);
        bucket += 1;
    }
    i = 0;
    while i < input.len()
    /*PROOF-BEGIN*/
        invariant
            i <= input.len(),
            present.len() == bucket_count,
            forall|j: int| 0 <= j < input.len() ==> input@[j] < bucket_count,
            forall|b: usize| b < bucket_count ==> (present@[b as int] <==> input@.take(i as int).contains(b)),
        decreases input.len() - i,
    /*PROOF-END*/
    {
        present[input[i]] = true;
        /*PROOF-BEGIN*/ proof {
            assert(input@.take((i + 1) as int) == input@.take(i as int).push(input@[i as int]));
        } /*PROOF-END*/
        i += 1;
    }
    let mut output: Vec<usize> = Vec::new();
    bucket = 0;
    while bucket < bucket_count
    /*PROOF-BEGIN*/
        invariant
            bucket <= bucket_count,
            present.len() == bucket_count,
            sorted(output@),
            output.len() <= bucket,
            forall|j: int| 0 <= j < output.len() ==> output@[j] < bucket,
            forall|j: int| 0 <= j < input.len() ==> input@[j] < bucket_count,
            forall|b: usize| b < bucket_count ==> (present@[b as int] <==> input@.contains(b)),
            forall|b: usize| output@.contains(b) <==> (b < bucket && input@.contains(b)),
        decreases bucket_count - bucket,
    /*PROOF-END*/
    {
        if present[bucket] {
            output.push(bucket);
        }
        bucket += 1;
    }
    /*PROOF-BEGIN*/ proof { membership_length_bound(output@, input@); } /*PROOF-END*/
    Ok(output)
}




#[inline]
pub fn stamp_precedes_snapshot(stamp: u64, transaction_id: u64) -> (result: bool)/*PROOF-BEGIN*/
 ensures result <==> stamp < transaction_id, /*PROOF-END*/ {
    stamp < transaction_id
}



}

}
verus! {
broadcast use vstd::seq_lib::group_seq_properties;

#[derive(PartialEq, Eq, Debug)]
pub enum Error { SerializationFailure, Index }
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct IndexRead { pub index_offset: usize, pub bucket: usize, pub stamp: u64 }
pub struct Transaction { pub txid: u64, pub index_conflict: bool, pub index_reads: Vec<IndexRead> }

pub open spec fn same_key(a: IndexRead, b: IndexRead) -> bool {
    a.index_offset == b.index_offset && a.bucket == b.bucket
}
pub open spec fn unique(reads: Seq<IndexRead>) -> bool {
    forall|i: int, j: int| 0 <= i < j < reads.len() ==> !same_key(reads[i], reads[j])
}
pub open spec fn unique_buckets(buckets: Seq<usize>) -> bool {
    forall|i: int, j: int| 0 <= i < j < buckets.len() ==> buckets[i] != buckets[j]
}
pub open spec fn suffix_from_processed(reads: Seq<IndexRead>, prior_len: int,
    offset: usize, processed: Seq<usize>) -> bool {
    forall|i: int| prior_len <= i < reads.len() ==>
        reads[i].index_offset == offset && processed.contains(reads[i].bucket)
}

// These proof-only callers use the actual extracted production kernels. Their
// postconditions supply the new capture premise, not an independent axiom.
pub fn canonical_sort_for_capture(input: &[usize]) -> (r: Result<Vec<usize>, usize>)
    ensures r.is_ok() ==> unique_buckets(r.unwrap()@),
{
    let r = bucket_kernels::canonical_buckets_sort(input, 4096);
    r
}
pub fn canonical_bitmap_for_capture(input: &[usize]) -> (r: Result<Vec<usize>, usize>)
    ensures r.is_ok() ==> unique_buckets(r.unwrap()@),
{
    let r = bucket_kernels::canonical_buckets_bitmap(input, 4096);
    r
}

pub proof fn prior_prefix_covers_current_bucket(reads: Seq<IndexRead>, prior_len: int,
    offset: usize, buckets: Seq<usize>, position: int)
    requires 0 <= prior_len <= reads.len(), 0 <= position < buckets.len(),
        unique_buckets(buckets),
        suffix_from_processed(reads, prior_len, offset, buckets.take(position)),
    ensures forall|i: int| prior_len <= i < reads.len() ==>
        reads[i].index_offset != offset || reads[i].bucket != buckets[position],
{
    assert forall|i: int| prior_len <= i < reads.len() implies
        reads[i].index_offset != offset || reads[i].bucket != buckets[position] by {
        let j = choose|j: int| 0 <= j < buckets.take(position).len()
            && buckets.take(position)[j] == reads[i].bucket;
        assert(buckets[j] != buckets[position]);
    }
}

pub proof fn duplicate_bucket_requires_canonicalization(read: IndexRead)
    ensures !unique_buckets(seq![read.bucket, read.bucket]),
        !unique(seq![read, read]),
{
    let repeated = seq![read, read];
    assert(same_key(repeated[0], repeated[1]));
    assert(!unique(repeated));
}
pub open spec fn captured(reads: Seq<IndexRead>, offset: usize, bucket: usize, stamp: u64) -> bool {
    reads.contains(IndexRead { index_offset: offset, bucket, stamp })
}
pub open spec fn extends(before: Seq<IndexRead>, after: Seq<IndexRead>) -> bool {
    before.len() <= after.len()
        && forall|i: int| 0 <= i < before.len() ==> before[i] == after[i]
}
pub open spec fn permitted_additions(before: Seq<IndexRead>, after: Seq<IndexRead>,
    offset: usize, buckets: Seq<usize>, stamps: Map<usize, u64>) -> bool {
    forall|r: IndexRead| after.contains(r) ==> before.contains(r)
        || (r.index_offset == offset && buckets.contains(r.bucket)
            && stamps.contains_key(r.bucket) && r.stamp == stamps[r.bucket])
}

// Abstracts only the standard iterator's first matching element, not native
// validation. The lowering is executable and itself verified here.
pub fn find_read_prefix(reads: &Vec<IndexRead>, prior_len: usize, offset: usize, bucket: usize)
    -> (r: Option<IndexRead>)
    requires prior_len <= reads.len(),
    ensures
        r.is_some() ==> exists|i: int| 0 <= i < prior_len && reads[i] == r.unwrap()
            && r.unwrap().index_offset == offset && r.unwrap().bucket == bucket
            && forall|j: int| 0 <= j < i ==>
                reads[j].index_offset != offset || reads[j].bucket != bucket,
        r.is_none() ==> forall|i: int| 0 <= i < prior_len ==>
            reads[i].index_offset != offset || reads[i].bucket != bucket,
{
    let mut i = 0;
    while i < prior_len
        invariant i <= prior_len <= reads.len(),
            forall|j: int| 0 <= j < i ==> reads[j].index_offset != offset || reads[j].bucket != bucket,
        decreases prior_len - i,
    {
        let read = &reads[i];
        if read.index_offset == offset && read.bucket == bucket { return Some(*read); }
        i += 1;
    }
    None
}

pub trait CaptureIndex {
    spec fn offset(&self) -> usize;
    spec fn stamps(&self) -> Map<usize, u64>;
    spec fn held(&self) -> Set<usize>;
    fn header_offset(&self) -> (r: usize) ensures r == self.offset();
    fn transactional_stamp(&self, bucket: usize) -> (r: Result<u64, Error>)
        requires self.held().contains(bucket), self.stamps().contains_key(bucket),
        ensures r.is_ok() ==> r.unwrap() == self.stamps()[bucket],
            r.is_err() ==> r == Err(Error::Index);
}

pub proof fn appended_read_preserves_unique(reads: Seq<IndexRead>, next: IndexRead)
    requires unique(reads),
        forall|i: int| 0 <= i < reads.len() ==> !same_key(reads[i], next),
    ensures unique(reads.push(next)),
{
    assert forall|i: int, j: int| 0 <= i < j < reads.push(next).len()
        implies !same_key(reads.push(next)[i], reads.push(next)[j]) by {
        if j < reads.len() { assert(!same_key(reads[i], reads[j])); }
    }
}

pub fn capture_dependencies<I: CaptureIndex>(index: &I, tx: &mut Transaction, buckets: &Vec<usize>)
    -> (result: Result<(), Error>)
    requires unique(old(tx).index_reads@), unique_buckets(buckets@),
        forall|i: int| 0 <= i < buckets.len() ==>
            index.held().contains(buckets[i]) && index.stamps().contains_key(buckets[i]),
    ensures
        final(tx).txid == old(tx).txid,
        old(tx).index_conflict ==> final(tx).index_conflict,
        result.is_ok() ==> final(tx).index_conflict == old(tx).index_conflict,
        unique(final(tx).index_reads@), extends(old(tx).index_reads@, final(tx).index_reads@),
        permitted_additions(old(tx).index_reads@, final(tx).index_reads@, index.offset(), buckets@, index.stamps()),
        final(tx).index_reads.len() <= old(tx).index_reads.len() + buckets.len(),
        result == Err(Error::SerializationFailure) ==> final(tx).index_conflict,
        result.is_ok() ==> forall|i: int| 0 <= i < buckets.len() ==>
            captured(final(tx).index_reads@, index.offset(), buckets[i], index.stamps()[buckets[i]])
                && index.stamps()[buckets[i]] < final(tx).txid,
{
    let ghost initial_reads = tx.index_reads@;
    let prior_read_len = tx . index_reads . len ( ) ;
    let mut bucket_pos = 0;
    while bucket_pos < buckets.len()
        invariant
            bucket_pos <= buckets.len(), unique(tx.index_reads@),
            unique_buckets(buckets@), prior_read_len == initial_reads.len(),
            initial_reads == old(tx).index_reads@, extends(initial_reads, tx.index_reads@),
            suffix_from_processed(tx.index_reads@, prior_read_len as int, index.offset(),
                buckets@.take(bucket_pos as int)),
            permitted_additions(initial_reads, tx.index_reads@, index.offset(), buckets@, index.stamps()),
            tx.index_reads.len() <= initial_reads.len() + bucket_pos,
            tx.txid == old(tx).txid,
            old(tx).index_conflict ==> tx.index_conflict,
            tx.index_conflict == old(tx).index_conflict,
            forall|j: int| 0 <= j < buckets.len() ==>
                index.held().contains(buckets[j]) && index.stamps().contains_key(buckets[j]),
            forall|j: int| 0 <= j < bucket_pos ==>
                captured(tx.index_reads@, index.offset(), buckets[j], index.stamps()[buckets[j]])
                    && index.stamps()[buckets[j]] < tx.txid,
        decreases buckets.len() - bucket_pos,
    {
        let bucket = &buckets[bucket_pos];
let stamp = index . transactional_stamp ( * bucket ) ? ;
if ! stamp_precedes_snapshot ( stamp , tx . txid ) {
    tx . index_conflict = true ;
    return Err ( Error :: SerializationFailure ) ;
}
let previous = if tx . index_reads . len ( ) == prior_read_len {
    {
        proof { assert(tx.index_reads.len() == prior_read_len); }
        find_read_prefix ( & tx . index_reads , tx . index_reads . len ( ) , index . header_offset ( ) , * bucket )
    }
}
else {
    find_read_prefix ( & tx . index_reads , prior_read_len , index . header_offset ( ) , * bucket )
}
;
if let Some ( previous ) = previous {
    if previous . stamp != stamp {
        tx . index_conflict = true ;
        return Err ( Error :: SerializationFailure ) ;
    }
}
else {
    proof {
        prior_prefix_covers_current_bucket(tx.index_reads@, prior_read_len as int,
            index.offset(), buckets@, bucket_pos as int);
        appended_read_preserves_unique(tx.index_reads@, IndexRead {
            index_offset: index.offset(), bucket: *bucket, stamp });
    }
    tx . index_reads . push ( IndexRead {
        index_offset : index . header_offset ( ) , bucket : * bucket , stamp ,
    }
    ) ;
}
        bucket_pos += 1;
    }
    Ok(())
}
}
verus! { pub fn stamp_precedes_snapshot(stamp: u64, transaction_id: u64) -> (r: bool)
ensures r == (stamp < transaction_id),
{ stamp < transaction_id } }
